/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cocktailapp1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author azeez
 */
public class CocktailApp extends javax.swing.JFrame {
      ArrayList<Cocktail> cocktails=new ArrayList<>();
    ArrayList<String> cknames=new ArrayList<>();
    ArrayList<Ingredients> arr3 = new ArrayList<>();
    private int x=1;
     private static Blender blender = new Blender(1500);
    private static int countOfCalories;
    private static int countOfVolume;
    private static int countNumberOfFruits;
    private int nc;
    
    private String info;
 void addFruit(String name, Color color, int caloriesPerUnit, double volumePerUnit){
         int numberOfFruits = Integer.parseInt(numberTextField.getText());
         if (numberOfFruits > 0) {
            Fruit fruit = new Fruit(name, color, caloriesPerUnit * numberOfFruits, volumePerUnit * numberOfFruits);
             try {
                blender.addIngredient(fruit);
                countOfCalories += fruit.getNomberOfCalories();
                countOfVolume += fruit.getVolume();
                countNumberOfFruits += numberOfFruits;
                arr3.add(fruit);
          } catch (BlenderOverFlowException e) {
              JOptionPane.showMessageDialog(this,e.getMessage());
            }
        } else {
              JOptionPane.showMessageDialog(this, "Invalid number of fruits");
        }
 }
 void addMilk(String type, int caloriesPerUnit) {
        Milk milk = new Milk(type, new Color(255, 255, 255), 20 * countNumberOfFruits, caloriesPerUnit * countNumberOfFruits);
        try {
            blender.addIngredient(milk);
            countOfCalories += milk.getNomberOfCalories();
            countOfVolume += milk.getVolume();
            arr3.add(milk);
        } catch (BlenderOverFlowException e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
 void addSugar(String type, int caloriesPerUnit) {
        Sugar sugar = new Sugar(type, new Color(255, 255, 224), 5 * countNumberOfFruits, caloriesPerUnit * countNumberOfFruits);
        try {
            blender.addIngredient(sugar);
            countOfCalories += sugar.getNomberOfCalories();
            countOfVolume+=sugar.getVolume();
            arr3.add(sugar);
        } catch (BlenderOverFlowException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * Creates new form CocktailApp
     */
    public CocktailApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        numberTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fruitList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        milkList = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        sugerList = new javax.swing.JList<>();
        makeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cupTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        currentVolume = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cocktailList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTextFieldActionPerformed(evt);
            }
        });

        fruitList.setBorder(javax.swing.BorderFactory.createTitledBorder("Fruit type"));
        fruitList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- Apple", "2- Banana", "3- Kiwi", "4- Strawberry", "5- Orange", "6- Blueberry" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fruitList);

        addButton.setText("add fruit");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("number of fruit");

        milkList.setBorder(javax.swing.BorderFactory.createTitledBorder("Milk type"));
        milkList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- Whole-Fat Milk", "2- Reduced-Fat Milk", "3- Low-Fat Milk", "4- Fat-Free Milk", "5- Without Milk" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(milkList);

        sugerList.setBorder(javax.swing.BorderFactory.createTitledBorder("Sugar type"));
        sugerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- White Sugar", "2- Brown Sugar", "3- Cane Sugar", "4- Raw Sugar", "5- Turbinado Sugar" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(sugerList);

        makeButton.setText("make cocktail");
        makeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("number of cups");

        jLabel3.setText("The mixer size 1.5 liter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addComponent(jSeparator1)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(makeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(addButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(cupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeButton)
                    .addComponent(currentVolume))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("make cocktail", jPanel1);

        cocktailList.setBorder(javax.swing.BorderFactory.createTitledBorder("Cocktails"));
        cocktailList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cocktailListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(cocktailList);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("information"));

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        jScrollPane5.setViewportView(infoTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("cocktail information", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        int index = fruitList.getSelectedIndex();
        switch (index) {
                case 0:
                    addFruit("Apple", new Color(255, 0, 0), 104, 150);
                    
                    break;
                case 1:
                    addFruit("Banana", new Color(255, 255, 0), 105, 175.52);
                    break;
                case 2:
                    addFruit("Kiwi", new Color(0, 255, 0), 42, 45);
                    break;
                case 3:
                    addFruit("Strawberry", new Color(255, 0, 0), 194, 13.6);
                    break;
                case 4:
                    addFruit("Orange", new Color(255, 165, 0), 73, 154);
                    break;
                case 5:
                    addFruit("Blueberry", new Color(0, 0, 255), 80, 148);
                    break;
    }
        numberTextField.setText("");
       
    }//GEN-LAST:event_addButtonActionPerformed

    
    private void numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextFieldActionPerformed

    private void makeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeButtonActionPerformed
        // TODO add your handling code here:
        int index1 = milkList.getSelectedIndex();
       
        switch (index1) {
                case 0:
                    addMilk("Whole-Fat", 75);
                    break;
                case 1:
                    addMilk("Reduced-Fat", 61);
                    break;
                case 2:
                    addMilk("Low-Fat", 53);
                    break;
                case 3:
                    addMilk("Fat-Free", 42);
                    break;
                case 4:
                    // No milk added
                    break;
}


int index = sugerList.getSelectedIndex();
 switch (index) {
                case 0:
                    addSugar("White Sugar", 54);
                    break;
                case 1:
                    addSugar("Brown Sugar", 53);
                    break;
                case 2:
                    addSugar("Cane Sugar", 54);
                    break;
                case 3:
                    addSugar("Raw Sugar", 60);
                    break;
                case 4:
                    addSugar("Turbinado Sugar", 65);
                    break;
                
 }
        System.out.println(countOfCalories);
  int numberOfCups = Integer.parseInt(cupTextField.getText());
  String name= "cocktail" +x;
        cknames.add(name);
        System.out.println(countOfVolume);
    double clPervl=(double)countOfCalories/(double)countOfVolume;
    double cupvol;
     double leftOver;
    if((countOfVolume/numberOfCups)>300){
        cupvol=300;
        leftOver= countOfVolume%(cupvol*numberOfCups);
    }
    else{
        cupvol= countOfVolume/numberOfCups;
        leftOver= 0;
    }
    
    
    double clPerCup=clPervl * cupvol;
  info= "count of volume in blender: "+ countOfVolume +"\nnumber of cups : "+ numberOfCups + "\nnumber of calories in every cup: "+clPerCup+ "\nvolume per cup: "+ cupvol  
          + "\nvolume leftover : " + leftOver;
  Cocktail ck1 =new Cocktail(name, arr3,info);
  cocktails.add(ck1);
  String[] names = cknames.toArray(new String[0]);
  cocktailList.setListData(names);
  x++;

 
  countNumberOfFruits=0;
  countOfCalories=0;
  countOfVolume=0;
  cupTextField.setText("");
    }//GEN-LAST:event_makeButtonActionPerformed

     

    private void cocktailListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cocktailListValueChanged
        // TODO add your handling code here:
        infoTextArea.setText("");
int index = cocktailList.getSelectedIndex();
if(index != -1){
Cocktail ckk = cocktails.get(index);
infoTextArea.setText(ckk.getInfo());


}
    }//GEN-LAST:event_cocktailListValueChanged

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CocktailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CocktailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CocktailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CocktailApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CocktailApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JList<String> cocktailList;
    private javax.swing.JTextField cupTextField;
    private javax.swing.JLabel currentVolume;
    private javax.swing.JList<String> fruitList;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton makeButton;
    private javax.swing.JList<String> milkList;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JList<String> sugerList;
    // End of variables declaration//GEN-END:variables
}
